# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

homeassistant:
  customize: !include customize.yaml

  # For accessing certain folders
  allowlist_external_dirs:
    - "/config/collected_data"
    - "/media/securityCameras"

  packages:
    irrigation: !include irrigation.yaml
    pool: !include pool.yaml
    climate: !include climate.yaml
    energy: !include energy.yaml
    recorder: !include recorder.yaml
    external_access: !include external_access.yaml
    security: !include security.yaml
    ios: !include ios.yaml
    secret_automations: !include secret_automations.yaml
    thermostat: !include thermostat.yaml

logger:
  default: warn
  logs:
    edata.connectors: critical
    custom_components.esios.sensor: fatal
    homeassistant.components.onvif: error
  filters:
    homeassistant.components.sensor:
      - ".*is taking over 10 seconds.*"
    homeassistant.setup:
      - ".*is taking over 10 seconds.*"

# Text to speech
tts:
  - platform: google_translate

# EXTERNAL FILES
automation: !include automations.yaml
scene: !include scenes.yaml
script: !include scripts.yaml
frontend:
  themes: !include_dir_merge_named themes/

# SENSORS
sensor:
  - platform: time_date
    display_options:
      - "time"
      - "date_time"
#  - platform: command_line
#    name: pvpc
#    command: "python3 /config/pvpc/pvpc_obtain.py"
#    unit_of_measurement: "€"
#    value_template: '{{ value_json.Actual / 1000 }}'
#    scan_interval: 1800
#    command_timeout: 30
#    json_attributes:
#      - Maximo
#      - Minimo
#      - Media
#      - BajoMedia

notify:
  - name: miguel
    platform: telegram
    chat_id: !secret miguel_chat_id
  - name: lau
    platform: telegram
    chat_id: !secret lau_chat_id
  - name: group
    platform: telegram
    chat_id: !secret group_chat_id

# DEVICE TRACKER
device_tracker:
  - platform: google_maps
    username: miguelpdomotica@gmail.com
    scan_interval: 60
    max_gps_accuracy: 400 # meters

template:
  - binary_sensor:
      - name: Open windows mode
        icon: mdi:curtains
        state: "{{ states('binary_sensor.living_room_window_contact') }}"
