sensor:
  - platform: statistics
    name: "Exterior temperature mean over last 48 hours"
    entity_id: sensor.exterior_sensor_temperature
    state_characteristic: average_linear
    sampling_size: 500
    max_age:
      hours: 48
  - platform: statistics
    name: "Exterior humidity mean over last 48 hours"
    entity_id: sensor.exterior_sensor_humidity
    state_characteristic: average_linear
    sampling_size: 500
    max_age:
      hours: 48
  - platform: statistics
    name: "Exterior humidity minimum over last 48 hours"
    entity_id: sensor.exterior_sensor_humidity
    state_characteristic: value_min
    sampling_size: 500
    max_age:
      hours: 48
  - platform: history_stats
    name: North zone irrigation statistics
    entity_id: switch.north_zone_manual
    state: "on"
    type: time
    start: "{{ now().replace(hour=0, minute=0, second=0) }}"
    end: "{{ now() }}"
  - platform: history_stats
    name: South zone irrigation statistics
    entity_id: switch.south_zone_manual
    state: "on"
    type: time
    start: "{{ now().replace(hour=0, minute=0, second=0) }}"
    end: "{{ now() }}"