automation:
  - id: '1672357197244'
    alias: iOS actions
    description: ''
    trigger:
    - platform: event
      event_type: ios.action_fired
      event_data:
        actionID: open_wicket_door
      id: open_wicket_door
    - platform: event
      event_type: ios.action_fired
      event_data:
        actionID: open_main_gate
      id: open_main_gate
    - platform: event
      event_type: ios.action_fired
      event_data:
        actionID: toggle_garage_light
      id: toggle_garage_light
    - platform: event
      event_type: ios.action_fired
      event_data:
        actionID: open_path_gate
      id: open_path_gate
    - platform: event
      event_type: ios.action_fired
      event_data:
        actionID: toggle_porch_light
      id: toggle_porch_light
    - platform: event
      event_type: ios.action_fired
      event_data:
        actionID: arrive_home
      id: arrive_home
      context: {}
    condition:
      - condition: or
        conditions:
        - condition: template
          value_template: !secret iphone_papa_check
        - condition: template
          value_template: !secret iphone_mama_check
    action:
    - choose:
      - conditions:
        - condition: trigger
          id: open_wicket_door
        sequence:
        - service: button.press
          data: {}
          target:
            entity_id: button.wicket_door
      - conditions:
        - condition: trigger
          id: open_main_gate
        sequence:
        - service: cover.toggle
          data: {}
          target:
            entity_id: cover.main_gate
      - conditions:
        - condition: trigger
          id: open_path_gate
        sequence:
        - service: button.press
          data: {}
          target:
            entity_id: button.path_gate
      - conditions:
        - condition: trigger
          id: toggle_garage_light
        sequence:
        - service: light.toggle
          data: {}
          target:
            entity_id: light.luz_del_garaje
      - conditions:
        - condition: trigger
          id: toggle_porch_light
        sequence:
        - service: light.toggle
          data: {}
          target:
            entity_id: light.front_porch
      - conditions:
        - condition: trigger
          id:
          - arrive_home
        sequence:
        - service: script.arrive_home
          data: {}
    mode: single