# ALARM
alarm_control_panel:
  - platform: manual
    name: El_Niño_alarm
    code: !secret alarm_control_panel_code
    # To require the code to arm the alarm
    code_arm_required: true
    # Arm again after triggering
    disarm_after_trigger: false
    # Delay from arming and becoming armed, eg. to leave the house.
    arming_time: 10
    # Allow time to disarm the alarm before it triggers, eg. when arriving home
    delay_time: 15
    # Amount of time the alarm is triggered for
    trigger_time: 180
    disarmed:
      # Ensure the alarm can never be directly triggered when disarmed
      trigger_time: 0
    armed_away:
      arming_time: 10
      delay_time: 15
      trigger_time: 180
    armed_home:
      arming_time: 5
      delay_time: 0
      trigger_time: 180

# For checking when a new file is uploaded from the camera by FTP
folder_watcher:
  - folder: /media/securityCameras/entrada
  - folder: /media/securityCameras/fachadaSur
  - folder: /media/securityCameras/fachadaEste
  - folder: /media/securityCameras/Comedor

template:
  - trigger:
      - platform: time
        at: '12:00:00'
      - platform: event
        event_type: event_template_reloaded
      - platform: homeassistant
        event: start
    sensor:
      - name: 'Sunrise Offset'
        state: "{{ state_attr('sun.sun', 'next_rising') | as_datetime + timedelta(minutes=range(-10, 25) | random) }}"
        device_class: timestamp
      - name: 'Sunset Offset'
        state: "{{ state_attr('sun.sun', 'next_setting') | as_datetime + timedelta(minutes=range(-25, 10) | random) }}"
        device_class: timestamp