switch:
  # Virtual zone switches which toggle the relay and check others
  - platform: template
    name: ${upper_id} zone
    id: ${id}_virtual
    internal: True
    lambda: return (id(${id}).position == VALVE_OPEN && id(${master_id}).position == VALVE_OPEN);
    turn_on_action:
      - if:
          condition:
            - or:
              - switch.is_off: ${ac_adapter_id}
              - lambda: return (id(${master_id}).position == VALVE_CLOSED);
          then:
            - switch.turn_on: ${ac_adapter_id}
            - valve.open: ${master_id}
            - delay: 2s
      - valve.close: ${pool_id}
      - valve.open: ${id}
      - delay: 1s
      - component.update: ${id}_left
      - component.update: ${irrigation_id}_state
    turn_off_action:
      - script.execute: close_master_valve
      - delay: 3s
      - valve.close: ${id}
      - delay: 1s
      - component.update: ${id}_left
      - component.update: ${irrigation_id}_state
