script:
  - id: ${id}_start_transition
    then:
      - if:
          condition:
            switch.is_on: ${pool_id}_virtual
          then:
            - switch.turn_off: ${pool_id}_virtual
            - script.wait: ${pool_id}_stop_transition
      - script.execute: open_master_valve
      - script.wait: open_master_valve
      - valve.open: ${id}
  - id: ${id}_stop_transition
    then:
      - lambda: |-
          id(${id}_timestamps_off).publish_state(delete_first_timestamp(id(${id}_timestamps_off).state));
      - script.execute: close_master_valve
      - script.wait: close_master_valve
      - valve.close: ${id}

switch:
  # Virtual zone switches which toggle the relay and check others
  - platform: template
    name: ${upper_id} zone
    id: ${id}_virtual
    internal: True
    lambda: return (id(${id}).position == VALVE_OPEN && id(${master_id}).position == VALVE_OPEN);
    turn_on_action:
      - script.execute: ${id}_start_transition
      - script.wait: ${id}_start_transition
      - script.execute: update_state_text
    turn_off_action:
      - script.execute: ${id}_stop_transition
      - script.wait: ${id}_stop_transition
      - script.execute: update_state_text
    on_state:
      - component.update: ${id}_left
