script:
  - id: turn_off_main_valve
    then:
      - if:
          condition:
            lambda: return (int(id(${north_id}_valve).state) + int(id(${south_id}_valve).state) + int(id(${pool_id}_valve).state) <= 1);
          then:
            - switch.turn_off: ${main_id}_valve
            - delay: 2s
            - switch.turn_off: ${ac_adapter_id}
