switch:
  # Virtual zone switches which toggle the relay and check others
  - platform: template
    name: ${upper_id} zone
    id: ${id}_virtual
    internal: True
    lambda: return (id(${id}_valve).state && id(${main_id}_valve).state);
    optimistic: true
    turn_on_action:
      - if:
          condition:
            - or:
              - switch.is_off: ${ac_adapter_id}
              - switch.is_off: ${main_id}_valve
          then:
            - switch.turn_on: ${ac_adapter_id}
            - switch.turn_on: ${main_id}_valve
            - delay: 2s
      - switch.turn_off: ${pool_id}_valve
      - switch.turn_on: ${id}_valve
      - delay: 1s
      - component.update: ${id}_left
      - component.update: ${irrigation_id}_state
    turn_off_action:
      - script.execute: turn_off_main_valve
      - delay: 3s
      - switch.turn_off: ${id}_valve
      - delay: 1s
      - component.update: ${id}_left
      - component.update: ${irrigation_id}_state
