script:
  - id: ${id}_start_transition
    then:
      - if:
          condition:
            switch.is_on: ${north_id}_virtual
          then:
            - switch.turn_off: ${north_id}_virtual
            - script.wait: ${north_id}_stop_transition
      - if:
          condition:
            switch.is_on: ${south_id}_virtual
          then:
            - switch.turn_off: ${south_id}_virtual
            - script.wait: ${south_id}_stop_transition
      - script.execute: open_master_valve
      - script.wait: open_master_valve
      - valve.open: ${id}
  - id: ${id}_stop_transition
    then:
      - lambda: |-
          id(${id}_timestamps_off).publish_state(delete_first_timestamp(id(${id}_timestamps_off).state));
      - script.execute: close_master_valve
      - script.wait: close_master_valve
      - valve.close: ${id}
      - homeassistant.service:
          service: esphome.pool_filling_completed
      - lambda: id(${id}_filling_requested) = false;

switch:
  - platform: template
    name: Pool filling
    id: ${id}_virtual
    internal: True
    lambda: return (id(${id}).position == VALVE_OPEN && id(${master_id}).position == VALVE_OPEN);
    turn_on_action:
      - script.execute: ${id}_start_transition
    turn_off_action:
      - script.execute: ${id}_stop_transition
    on_state:
      - component.update: ${id}_left
      - component.update: ${irrigation_id}_state
