switch:
  #### Pump relay switch
  - platform: gpio
    name: ${pump_upper_id}
    id: ${pump_id}
    internal: True
    pin:
      number: ${pump_relay_pin}
      inverted: True
    restore_mode: ALWAYS_OFF
    on_turn_on:
      - component.update: pump_left
    on_turn_off:
      - component.update: pump_left

# ============================================================================ #
binary_sensor:
  - platform: gpio
    pin:
      number: ${pump_running_sensor_pin}
      mode:
        input: true
    name: ${pump_upper_id} running
    id: ${pump_id}_running_sensor
    icon: mdi:pump
    device_class: running
    filters:
      delayed_on_off: 50ms

  - platform: gpio
    pin:
      number: ${pump_manual_physical_switch_pin}
      mode:
        input: True
        pulldown: True
    name: ${pump_upper_id} manual switch (debug)
    id: pump_manual_physical_switch
    filters:
      delayed_on_off: 70ms
    on_state:
      then:
        - lambda: |-
            if (id(pump_manual_physical_switch).state) id(${pump_id}_manual).turn_on();
            else if (!id(pump_manual_physical_switch).state) id(${pump_id}_manual).turn_off();

  - platform: gpio
    pin:
      number: ${pump_automation_physical_switch_pin}
      mode:
        input: True
        pulldown: True
    name: ${pump_upper_id} automation switch (debug)
    id: pump_automation_physical_switch
    filters:
      delayed_on_off: 40ms
    on_state:
      then:
        - lambda: |-
            if (id(pump_automation_physical_switch).state){
              auto call = id(${pump_id}_mode).make_call();
              call.set_option("Automatic");
              call.perform();
            }
            else if (!id(pump_automation_physical_switch).state) {
              id(${pump_id}_manual).turn_off();
            }
