switch:
  #### Relay for the AC adaptor
  - platform: gpio
    id: $ac_adapter_id
    icon: mdi:connection
    pin:
      number: $ac_adapter_pin
      inverted: true
    name: "Adaptador AC"
    restore_mode: ALWAYS_OFF