api:
  services:
    - service: reset_${id}_next_irrigation_day
      then:
        - component.update: ${id}_next_irrigation_day

# ============================================================================ #
text_sensor:
  #### Next day of irrigation, based in temperature, rain...
  - platform: template
    id: ${id}_next_irrigation_day
    internal: True
    lambda: return to_string(id(time_sntp).now().timestamp);
    update_interval: never
    on_value: 
      then:
        - component.update: ${id}_next_irrigation_ha_day
  - platform: template
    name: ${upper_id} next irrigation day
    id: ${id}_next_irrigation_ha_day
    lambda: return get_time_formated(id(${id}_next_irrigation_day).state);
    update_interval: never