esphome:
  on_boot:
    priority: 800.0
    then:
      - delay: 30s

globals:
  #### Bool to save filling state
  - id: pool_filling_bool
    type: bool
    restore_value: yes
  - id: pool_filling_requested
    type: bool
    restore_value: yes
  - id: filling_rn
    type: bool
    restore_value: yes
  - id: secure_pumping
    type: bool
    restore_value: yes

# ============================================================================ #
api:
  services:
    - service: filling_start
      then:
        - switch.turn_off: pool_pump
        - delay: 2s
        - lambda: id(filling_rn) = true;
        - homeassistant.service: # Opens the valve
            service: esphome.irrigation_filling_start
        - script.execute: pool_filling_request_loop
    - service: manual_filling_start
      then:
        - switch.turn_off: pool_pump
        - delay: 2s
        - lambda: id(filling_rn) = true;
        - homeassistant.service:
            service: esphome.irrigation_filling_start
    - service: filling_completed
      then:
        - lambda: |-
            id(filling_rn) = false;
            id(pool_filling_requested) = false;
            if (id(pump_next_on).state != "Sin programaciones" && id(pump_next_off).state != "Sin programaciones" &&
            id(pump_next_on).state > id(pump_next_off).state && id(secure_pumping))
              id(pool_pump).turn_on();
    - service: filling_requested
      then:
        - lambda: |-
            id(pool_filling_requested) = true;

# ============================================================================ #
script:
  - id: pool_filling_request_loop
    then:
      - while:
          condition:
            and:
              - binary_sensor.is_off: pool_high_level
          then:
            - homeassistant.service:
                service: esphome.irrigation_request_more_pool_water
            - delay: 60s
  - id: pool_filling_request_today
    then:
      - homeassistant.service:
          service: esphome.irrigation_request_pool_water

# ============================================================================ #
time:
  - platform: homeassistant
    id: time_filling
    timezone: Europe/Madrid
    on_time:
      - seconds: 30
        minutes: /1
        then:
          - lambda: |-
              if (id(pool_filling_bool) && !id(pool_high_level).state && !id(pool_filling_requested)) {
                id(pool_filling_request_today).execute();
              }
