# static_ip: 10.133.100.64

esp32:
  board: esp32-poe
  framework:
    type: arduino

esphome:
  name: $name

ota:
  platform: esphome
  password: !secret ota_pool

# Enable logging
logger:

# Enable Home Assistant API
api:
