# static_ip: 10.133.100.63

esp32:
    board: esp-wrover-kit
    framework:
        type: arduino

esphome:
  name: ${name}

# Enable Home Assistant API
api:

ota:
  password: !secret ota_irrigation

# Enable logging
logger:
