# static_ip: 10.133.100.73

esp32:
    board: esp-wrover-kit
    framework:
        type: arduino

ota:
    platform: esphome
    password: !secret ota_heater

# Enable logging
logger:

# Enable Home Assistant API
api:
    encryption:
        key: !secret api_heater
