esphome:
  name: ${name}

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_murcia_heater

ota:
  password: !secret ota_murcia_heater

# wifi:
#   use_address: !secret murcia_heater_address