globals:
  - id: ${id}
    type: float
    restore_value: True

# ============================================================================ #
sensor:
  - platform: homeassistant
    id: ui_${id}
    entity_id: ${entity_id}
    on_value:
      then:
        - lambda: id(${id}) = id(ui_${id}).state;