switch:
  - platform: template
    name: ${upper_id} automatic mode
    icon: mdi:refresh-auto
    id: ${id}_automatic_mode
    restore_mode: RESTORE_DEFAULT_OFF
    optimistic: True
    on_turn_on:
      - script.execute: ${id}_update_time
    on_turn_off:
      - script.execute: ${id}_update_time