globals:
  - id: ${id}_automation_bool
    type: bool
    restore_value: True

# ============================================================================ #
switch:
  - platform: template
    name: ${upper_id} automation
    icon: mdi:refresh-auto
    id: ${id}_automation
    lambda: return id(${id}_automation_bool);
    turn_on_action:
      - lambda: |-
          id(${id}_automation_bool) = true;
      - script.execute: ${id}_update_time
    turn_off_action:
      - lambda: |-
          id(${id}_automation_bool) = false;
      - script.execute: ${id}_update_time