sensor:
  ## Next cycle duration
  - platform: template
    name: ${upper_id} next duration
    id: ${id}_next_duration
    update_interval: never
    accuracy_decimals: 0
    unit_of_measurement: min
    icon: mdi:timer-outline
    lambda: |-
      if (id(${id}_next_on).state == "Sin programaciones" || id(${id}_next_off).state == "Sin programaciones") 
        return 0;
      if (atoi((id(${id}_next_off).state).c_str()) > atoi((id(${id}_next_on).state).c_str())) {
        return ((atoi((id(${id}_next_off).state).c_str()) - atoi((id(${id}_next_on).state).c_str())) / 60);
      }
      return id(${id}_next_duration).state;