text_sensor:
  ## Next cycle duration
  - platform: template
    name: ${upper_id} next duration
    id: ${id}_next_duration
    update_interval: never
    icon: mdi:timer-outline
    lambda: |-
      if (id(${id}_next_on).state == "Sin programaciones" || id(${id}_next_off).state == "Sin programaciones") 
        return {"0 min"};
      if (atoi((id(${id}_next_off).state).c_str()) > atoi((id(${id}_next_on).state).c_str())) {
        int mins = ((atoi((id(${id}_next_off).state).c_str()) - atoi((id(${id}_next_on).state).c_str())) / 60);
        int hours = mins/60;
        mins %= 60;
        string ret = to_string(mins) + " min";

        if(hours != 0) ret.insert(0, to_string(hours) + " h ");
        return {ret};
      }
      return {};