substitutions:
  upper_name: Exterior alarm
  name: exterior_alarm
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password

packages:
  device_base: !include common/device_base.exterior-alarm.yaml
  basic_control: !include common/basic_control.yaml
  wifi: !include common/wifi.yaml

esphome:
  name: exterior-alarm
  includes:
  - BarrierSensor.h

# ============================================================================ #
binary_sensor:
  - platform: custom
    lambda: |-
      auto myBarr = new BarrierSensor();
      App.register_component(myBarr);
      return {myBarr->Barriers[0], myBarr->Barriers[1], myBarr->Barriers[2], myBarr->Barriers[3], myBarr->Barriers[4], myBarr->Barriers[5], myBarr->Tampers[0], myBarr->Tampers[1], myBarr->Tampers[2], myBarr->Tampers[3], myBarr->Tampers[4], myBarr->Tampers[5]};

    binary_sensors:
      - name: "Barrera Norte"
        publish_initial_state: True
        device_class: safety
        filters:
          delayed_on_off: 700ms
      - name: "Ventana del Salón"
        publish_initial_state: True
        device_class: safety
        filters:
          delayed_on_off: 700ms
      - name: "Barrera Sur"
        publish_initial_state: True
        device_class: safety
        filters:
          delayed_on_off: 700ms
      - name: "Barrera Este"
        publish_initial_state: True
        device_class: safety
        filters:
          delayed_on_off: 700ms
      - name: "Barrera Noroeste"
        publish_initial_state: True
        device_class: safety
        filters:
          delayed_on_off: 700ms
      - name: "Barrera Oeste"
        publish_initial_state: True
        device_class: safety
        filters:
          delayed_on_off: 700ms
      - name: "Barrera Norte Tamper"
        publish_initial_state: True
        device_class: opening
        filters:
          delayed_on_off: 700ms
      - name: "Ventana del Salón Tamper"
        publish_initial_state: True
        device_class: opening
        filters:
          delayed_on_off: 700ms
      - name: "Barrera Sur Tamper"
        publish_initial_state: True
        device_class: opening
        filters:
          delayed_on_off: 700ms
      - name: "Barrera Este Tamper"
        publish_initial_state: True
        device_class: opening
        filters:
          delayed_on_off: 700ms
      - name: "Barrera Noroeste Tamper"
        publish_initial_state: True
        device_class: opening
        filters:
          delayed_on_off: 700ms
      - name: "Barrera Oeste Tamper"
        publish_initial_state: True
        device_class: opening
        filters:
          delayed_on_off: 700ms