substitutions:
  upper_name: Exterior alarm
  name: exterior_alarm
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password

packages:
  device_base: !include common/device_base.exterior-alarm.yaml
  basic_control: !include common/basic_control.yaml
  wifi: !include common/wifi.yaml
  alarm_adc: !include alarm/adc_setup.yaml
  barrier_north: !include
    file: alarm/sensor_pair.yaml
    vars:
      id: barrier_north
      name: Barrera Norte
      pin: 32
  living_room_window: !include
    file: alarm/sensor_pair.yaml
    vars:
      id: living_room_window
      name: Ventana del Salón
      pin: 33
  barrier_south: !include
    file: alarm/sensor_pair.yaml
    vars:
      id: barrier_south
      name: Barrera Sur
      pin: 34
  barrier_east: !include
    file: alarm/sensor_pair.yaml
    vars:
      id: barrier_east
      name: Barrera Este
      pin: 35
  barrier_northwest: !include
    file: alarm/sensor_pair.yaml
    vars:
      id: barrier_northwest
      name: Barrera Noroeste
      pin: 36
  barrier_west: !include
    file: alarm/sensor_pair.yaml
    vars:
      id: barrier_west
      name: Barrera Oeste
      pin: 39

esphome:
  name: exterior-alarm
