substitutions:
  name: madrid-proxy
  upper_name: Madrid proxy
  wifi_ssid: !secret madrid_wifi_ssid
  wifi_password: !secret madrid_wifi_password

packages:
  device_base: !include common/device_base.madrid-proxy.yaml
  basic_control: !include common/basic_control.yaml
  wifi: !include common/wifi.yaml

esp32_ble_tracker:
  scan_parameters:
    interval: 1100ms
    window: 1100ms
    active: False

bluetooth_proxy: