substitutions:
  name: pool
  upper_name: Swimming pool
  pump_id: pump
  pump_upper_id: Pool pump
  ####
  low_level_sensor_pin: "36"
  high_level_sensor_pin: "35"
  pump_running_sensor_pin: "39"
  pool_lights_physical_switch_pin: "34"
  pump_relay_pin: "33"
  pool_lights_relay_pin: "32"
  pump_manual_physical_switch_pin: "16"
  pump_automation_physical_switch_pin: "13"
  rain_sensor_pin: "3"
  #### Do not use pin 14, as it caused some errors restarting the device when pulled down

esphome:
  name: $name
  includes:
    - time_control.hpp
    - pool.hpp

packages:
  device_base: !include common/device_base.pool.yaml
  ethernet: !include common/olimex-esp32-poe.config.yaml
  basic_control: !include common/basic_control.yaml
  time: !include common/time.yaml
  sun: !include common/sun.yaml
  debug: !include pool/debug.yaml
  ha_parameters: !include pool/ha_parameters.yaml
  pluviometer: !include pool/pluviometer.yaml
  pool_lights: !include pool/pool_lights.yaml
  pool_level_sensor: !include pool/pool_level.yaml
  pool_filling: !include pool/pool_filling.yaml
  pump_gpio: !include pool/pump/pump_gpio.yaml
  pump_logic: !include pool/pump/pump_logic.yaml
  ####
  pump_text_sensor: !include
    file: common/time_controlled_entity/text_sensor.yaml
    vars:
      id: ${pump_id}
      upper_id: ${pump_upper_id}
  pump_next_duration: !include
    file: common/time_controlled_entity/next_duration_sensor.yaml
    vars:
      id: ${pump_id}
      upper_id: ${pump_upper_id}

# Enable Home Assistant API
api:
